### ISSUE TITLE
Upgrade bro to 2.5.3

### ISSUE THREAD

**Issue by JonZeolla** [Security-Onion-Solutions/securityonion-docker#3]
https://github.com/Security-Onion-Solutions/securityonion-docker/blob/651c3d5c97d55c5550e6700a81c51fd919d3a36f/so-bro/Dockerfile#L16 should be able to point to https://github.com/Security-Onion-Solutions/securityonion-docker-rpm/releases/download/Bro_2.5.3/securityonion-bro-2.5.3.1-securityonion.rpm

Bro 2.5.4 has been released, but is not yet available in https://github.com/Security-Onion-Solutions/securityonion-docker-rpm

**Comment by dougburks** [comment]
Hi @JonZeolla ,

Thanks for the PR!  We're not really using this Docker image yet and that's why Bro 2.5.4 is not available at https://github.com/Security-Onion-Solutions/securityonion-docker-rpm.  But we'll be moving towards it in the future!
