### ISSUE TITLE
Could you teach me how to use securityonion on the docker

### ISSUE THREAD

**Issue by SuperMike96** [Security-Onion-Solutions/securityonion-docker#6]
I'd like to deploy the securityonion on my server. However, it not allowed to use third-party image. So I decided to use the docker to deploy it. But since I installed so-kibana, I lost my mind, how could I read the schematic and does it mean deploy the securityonion?

**Comment by dougburks** [comment]
Hi @SuperMike96 ,

Please send all questions to the security-onion Google Group:
https://securityonion.readthedocs.io/en/latest/mailing-lists.html

Thanks!
